### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Moony00** [MatteoSchiavinato/all2vcf#1]
Good morning!
I got my .snps from mummer with '-T' and trying to get a vcf file with this tool.
Here's my traceback:

Traceback (most recent call last):
  File "~/all2vcf/src/mummer", line 362, in <module>
    Vcf_lines = [ convert_snps_to_vcf(line) for line in Lines ]
  File "~/all2vcf/src/mummer", line 362, in <listcomp>
    Vcf_lines = [ convert_snps_to_vcf(line) for line in Lines ]
  File "~/all2vcf/src/mummer", line 65, in convert_snps_to_vcf
    scaffold = lst[10]
IndexError: list index out of range

Here's my command:
"~/all2vcf/all2vcf" mummer --snps test.snps --reference ./Mumtest_rotunda.fasta

And, since I'm a noob here, maybe I did some mistakes while cloning this tool...
This is what I revised for using all2vcf.

#!/usr/bin/python3.6 
interpreter="python3.6"

Hope I didn't bother you too much.
And can't wait to get my VCF file with your tool! 
Thanks for your great effort.

**Comment by MatteoSchiavinato** [comment]
Good morning! Sorry for the belated response - it was evening where I live. So, I suspect that the issue you're having has something to do with this old issue of all2vcf's "grandfather": https://github.com/MatteoSchiavinato/Utilities/issues/1 

Let me know if it fixed it!

**Comment by ewoutcrombez** [comment]
Hello!
I am having the same or similar issue. I already looked at https://github.com/MatteoSchiavinato/Utilities/issues/1 but i am still not able to fix it...

I used this command:
`show-snps -T -C haplotype_genome_vs_reference.delta > haplotype_genome_vs_reference_unamb.snps`

and then used this command to convert the snps file to vcf:
`all2vcf mummer --input-header --snps haplotype_genome_vs_reference_unamb.snps --reference reference.fa`

and got the following error:
`Traceback (most recent call last):
  File "/scratch/recent_wgds/potato/nucmer/all2vcf/src/mummer", line 370, in <module>
    Vcf_lines = [ convert_snps_to_vcf(line) for line in Lines ]
  File "/scratch/recent_wgds/potato/nucmer/all2vcf/src/mummer", line 370, in <listcomp>
    Vcf_lines = [ convert_snps_to_vcf(line) for line in Lines ]
  File "/scratch/recent_wgds/potato/nucmer/all2vcf/src/mummer", line 63, in convert_snps_to_vcf
    scaffold = lst[10]
IndexError: list index out of range`

My snps file looks like this:
```
reference.fa haplotype.fasta
NUCMER

[P1]    [SUB]   [SUB]   [P2]    [BUFF]  [DIST]  [FRM]   [TAGS]
83023   A       G       13824246        42      83023   1       -1      00      Chr6
83065   G       A       13824204        27      83065   1       -1      00      Chr6
83092   G       A       13824177        27      83092   1       -1      00      Chr6
85074   G       A       13822192        40      85074   1       -1      00      Chr6
87801   T       G       13819465        48      87801   1       -1      00      Chr6
87849   T       G       13819417        48      87849   1       -1      00      Chr6
```

And if I do `head haplotype_genome_vs_reference_unamb.snps | awk '{print NF}'`
I get
```
2
1
0
8
10
10
10
10
10
10
```

I used MUMmer 4.0.0beta2.

Could you please help me solve this issue? Many thanks!!

**Comment by MatteoSchiavinato** [comment]
Based on your command, I see you're using `show-snps -T -C` and not `show-snps -CTlr`. Did you try with these options?

**Comment by ewoutcrombez** [comment]
Thank you for your quick response! I did not try this yet and will try it out now. I will let you know if it works using these options.

**Comment by ewoutcrombez** [comment]
Indeed, it works whe using `show-snps -CTlr` instead of `show-snps -T -C`! Thank you very much!

**Comment by MatteoSchiavinato** [comment]
Never mind, glad it helped!
