### ISSUE TITLE
Distribution of Indels

### ISSUE THREAD

**Issue by meiselex** [MatteoSchiavinato/all2vcf#2]
I generated a VCF using all2vcf and it worked fine.
Now with the generated VCF file, I used the command

`bcftools stats mummer_all2vcf.vcf | grep "^IDD" > mummer_all2vcf.stats_idd` 
 
to get an overview of the distribution of SV sizes. Do you have an idea why I only see Deletions and SNPs in the VCF but not a single variant greater than 1 bp?

**Comment by MatteoSchiavinato** [comment]
Can you send me the VCF file, the SNPS file? I can do some testing. Out of the blue I can't say :)

**Comment by meiselex** [comment]
Thanks for the fast response.
Here is the link for the VCF:
https://mega.nz/file/js9k0ZjL#PxCxR8Bscl521q5mmHKhog-9qm--uyLE2_jA1Q-quxI

(And here is the header that i used (extracted from SyRi):
https://mega.nz/file/Wl8nhZiS#DKXmIWSzBp-nFDtB3PhF19Vr_Sl-vCLVcunwb1DdwII)

**Comment by MatteoSchiavinato** [comment]
I'll have a look and get back at you (likely next week, maybe today!).

**Comment by MatteoSchiavinato** [comment]
Could you please send the `snps` file produced by nucmer, too? I'm testing it today to fix your problem.

**Comment by meiselex** [comment]
The snps file can be found here:
https://mega.nz/file/C5MWQJ5Y#T37UgREB4MZAq-S690fuyv1UOEosOnxQQLjtmeaQ9bQ

**Comment by MatteoSchiavinato** [comment]
Hi, I have corrected the code to account for the bug you spotted. Nice catch, happy to have fixed it! You can download the new release (v0.7.4) from the releases panel or simply git clone the repository.
